// client/src/components/NavBar.svelte
<script lang="ts">
	import { route } from '../lib/router';
</script>

<nav>
	<div class="logo">UsedMarket</div>

	<div class="links">
		<a href="#/" class:selected={$route === '#/'}>Home</a>
		<a href="#/about" class:selected={$route.startsWith('#/about')}>About</a>
	</div>
</nav>

<style>
	nav {
		display: flex;
		justify-content: space-between;
		align-items: center;
		padding: 1rem 2rem;
		background: #fff;
		border-bottom: 1px solid #eee;
		position: sticky;
		top: 0;
	}

	.logo {
		font-weight: 700;
	}

	.links {
		display: flex;
		gap: 1.5rem;
	}

	a {
		text-decoration: none;
		color: #333;
	}

	a.selected {
		font-weight: 700;
		color: #000;
	}
</style>

// client/src/components/NavBar.vue
<script setup lang="ts">
import { RouterLink } from "vue-router";
</script>

<template>
    <header class="navbar">
        <h1 class="logo">Trade-IT</h1>

        <nav class="nav-links">
            <RouterLink to="/">Dashboard</RouterLink>
            <RouterLink to="/about">About</RouterLink>
            <RouterLink to="/login">Login</RouterLink>
        </nav>
    </header>
</template>

<style scoped>
.navbar {
    display: flex;
    justify-content: space-between;
    align-items: center;

    padding: 1rem 1.5rem;
    background: #f5f5f5;
    box-shadow:  0 2px 1px #949494;
    
    border-radius: 3px;
}

/* Logo styling */
.logo {
    margin: 0;
    font-size: 1.4rem;
    font-weight: 600;
}

/* Navigation layout */
.nav-links {
    display: flex;
    gap: 1.2rem;
}

.nav-links a {
    color: #333;
    text-decoration: underline 3px;
    text-underline-offset: 6px;
    font-weight: 500;
    transition: color 0.2s ease;
}

.nav-links a:hover {
    color: #0078ff;
}

/* Optional: Active route styling */
.router-link-active {
    color: #0078ff;
    font-weight: 600;
}
</style>
